# Header
nav:
  Posts: /archives
  Categories: /category
  Tags: /tag

rss: /atom.xml

# favicon
favicon: /favicon.png

# logo
logo: /images/logo.svg

# links
links:
  Github: https://github.com/xbmlz
  ZhiHu:
  Twitter:
  Weibo:


# stylesheets loaded in the <head>
stylesheets:
  - /css/style.css

scripts:
  - /js/index.js
  - /js/iconify.min.js
