# Header
nav:
  Home: /
  Archives: /archives
  Tags: /tags
  About: /about

rss: /atom.xml

favicon: /favicon.png

logo: /images/logo.svg

# stylesheets loaded in the <head>
stylesheets:
  - /css/style.css

scripts:
  - /js/index.js
